/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { InsuranceProduct } from './insuranceProduct';
import { AuditLog } from './auditLog';
import { Claim } from './claim';


export interface Admin { 
    adminId?: number;
    username?: string | null;
    passwordHash?: string | null;
    email?: string | null;
    role?: string | null;
    lastLogin?: string | null;
    createdAt?: string | null;
    auditLogs?: Array<AuditLog> | null;
    claims?: Array<Claim> | null;
    insuranceProducts?: Array<InsuranceProduct> | null;
    policies?: Array<Policy> | null;
}

