/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Admin } from './admin';


export interface AuditLog { 
    logId?: number;
    adminId?: number;
    action?: string | null;
    entityType?: string | null;
    entityId?: number;
    ipAddress?: string | null;
    timestamp?: string | null;
    admin?: Admin;
}

