/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { Admin } from './admin';


export interface Claim { 
    claimId?: number;
    policyId?: number;
    claimDate?: string;
    amount?: number;
    description?: string | null;
    status?: string | null;
    processedBy?: number | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    policy?: Policy;
    processedByNavigation?: Admin;
}

