/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';


export interface Customer { 
    customerId?: number;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    kycStatus?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    policies?: Array<Policy> | null;
}

