/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsuranceProductDTO { 
    productName?: string | null;
    category?: string | null;
    description?: string | null;
    basePremium?: number;
}

