/**
 * InsuranceAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Agent } from './agent';
import { Customer } from './customer';
import { Admin } from './admin';
import { InsuranceProduct } from './insuranceProduct';
import { Claim } from './claim';


export interface Policy { 
    policyId?: number;
    policyNumber?: string | null;
    productId?: number;
    customerId?: number;
    agentId?: number | null;
    premium?: number;
    startDate?: string;
    endDate?: string;
    status?: string | null;
    approvedBy?: number | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    agent?: Agent;
    approvedByNavigation?: Admin;
    claims?: Array<Claim> | null;
    customer?: Customer;
    product?: InsuranceProduct;
}

